language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-24.0.3
    - build-tools-23.0.1
    - android-23
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'intel-android-extra-license.+'
env:
 - JAVA7_HOME=/usr/lib/jvm/java-7-oracle/jre
before_script:
  - tar -xvf vksdk_library.tar.gz && sleep 15
