language: android
jdk:
  - oraclejdk8
licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
android:
  components:
    - tools
    - build-tools-24.0.3
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
env:
 - JAVA7_HOME=/usr/lib/jvm/java-7-oracle/jre
before_script:
  - tar -xvf vksdk_library.tar.gz && sleep 15
